### DISCUSSION TITLE
Self Host configuration for custom domain

### DISCUSSION THREAD

**Discussion by nitanmarcel** [juspay/hyperswitch#7051] [Q&A]
Hello.

I can't figure out how to edit the configuration of hyperswitch to run on a separate port and what I need to modify to work with my invoice.example.com domain.

Could someone guide me?

Thanks

**Comment by SanchithHegde** [comment]
@nitanmarcel Could you include information as to how you have deployed Hyperswitch: is it via Docker Compose, Helm, or something else?

**Reply by nitanmarcel** [reply]
Ah sorry via docker compose.

I tried editing both the compose yaml and the config toml but when I try to register I get a 500 error

```
[server]
port = 8080
host = "0.0.0.0"
request_body_limit = 16_384 # Post request body is limited to 16k.

[log.file]
enabled = true # Whether you want to store log in log files.
path = "logs"   # Where to store log files.
level = "DEBUG" # What gets into log files.
# rotation = "60"           # mins # current framework doesn't support configuring rotation. set to hourly rotation.

[log.console]
enabled = true  # Whether you want to see log in your terminal.
level = "INFO" # What you see in your terminal.

[log.telemetry]
traces_enabled = false                                      # Whether traces are enabled.
metrics_enabled = true                                      # Whether metrics are enabled.
ignore_errors = false                                       # Whether to ignore errors during traces or metrics pipeline setup.
otel_exporter_otlp_endpoint = "https://otel-collector:4317" # Endpoint to send metrics and traces to.
use_xray_generator = false                                  # Set this to true for AWS X-ray compatible traces
bg_metrics_collection_interval_in_secs = 15                 # Interval for collecting the metrics in background thread

[master_database]
username = "hyperswitch"
password = "1234"
host = "172.31.0.1"
port = 5432
dbname = "hyperswitch_db"
pool_size = 5

[forex_api]
call_delay = 21600
local_fetch_retry_count = 5
local_fetch_retry_delay = 1000
api_timeout = 20000
api_key = "YOUR API KEY HERE"
fallback_api_key = "YOUR API KEY HERE"
redis_lock_timeout = 26000

[replica_database]
username = "db_user"
password = "db_pass"
host = "pg"
port = 5432
dbname = "hyperswitch_db"
pool_size = 5

[secrets]
admin_api_key = "1234"
jwt_secret = 1234
master_enc_key = "73ad7bbbbc640c845a150f67d058b279849370cd2c1f3c67c4dd6c869213e13a"

[user]
password_validity_in_days = 90
two_factor_auth_expiry_in_secs = 300
totp_issuer_name = "Hyperswitch"
base_url = "https://invoiceapi.marcelsoftware.dev"
force_two_factor_auth = false
force_cookies = false

[locker]
host = ""
host_rs = ""
mock_locker = true
basilisk_host = ""
locker_enabled = true
ttl_for_storage_in_secs = 220752000

[jwekey]
vault_encryption_key = ""
rust_locker_encryption_key = ""
vault_private_key = ""

[redis]
host = "redis-standalone"
port = 6379
cluster_enabled = false
cluster_urls = ["redis-cluster:6379"]
pool_size = 5
reconnect_max_attempts = 5
reconnect_delay = 5
default_ttl = 300
default_hash_ttl = 900
use_legacy_version = false
stream_read_count = 1
auto_pipeline = true
disable_auto_backpressure = false
max_in_flight_commands = 5000
default_command_timeout = 30
unresponsive_timeout = 10
max_feed_count = 200

[key_manager]
url = "http://localhost:5000"

[cors]
max_age = 30
origins = "http://localhost:8080,http://localhost:9000,https://marcelsoftware.dev,https://invoice.marcelsoftware.dev"
allowed_methods = "GET,POST,PUT,DELETE"
wildcard_origin = false

[refund]
max_attempts = 10
max_age = 365

[api_keys]
hash_key = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

```

**Reply by SanchithHegde** [reply]
If you just want the app server to listen on a different port on the host machine instead of `8080`, you should be able to update this snippet (for the `hyperswitch-server` service) in the `docker-compose.yml` file:

https://github.com/juspay/hyperswitch/blob/72904842ed0092e16e2d9980e1d4968df03cafb6/docker-compose.yml#L60-L61

to be something like:

```yaml
ports:
  - "8090:8080"
```

This should expose the application server (which listens on port `8080` within the container) on port `8090` on the host machine. You can refer to the [Docker Compose docs](https://docs.docker.com/reference/compose-file/services/#ports) for more information. You need not make any changes in the `config/docker_compose.toml` file to achieve this.

**Reply by nitanmarcel** [reply]
> If you just want the app server to listen on a different port on the host machine instead of `8080`, you should be able to update this snippet (for the `hyperswitch-server` service) in the `docker-compose.yml` file:
> 
> https://github.com/juspay/hyperswitch/blob/72904842ed0092e16e2d9980e1d4968df03cafb6/docker-compose.yml#L60-L61
> 
> to be something like:
> 
> ```yaml
> ports:
>   - "8090:8080"
> ```
> 
> This should expose the application server (which listens on port `8080` within the container) on port `8090` on the host machine. You can refer to the [Docker Compose docs](https://docs.docker.com/reference/compose-file/services/#ports) for more information. You need not make any changes in the `config/docker_compose.toml` file to achieve this.

I also removed the pg service since I have the database locally

I had to change the port `9000` to `9001` 

```
volumes:
  pg_data:
  redisinsight_store:
  ckh_data:

networks:
  bridge:

  migration_runner:
    image: rust:latest
    command: "bash -c 'cargo install diesel_cli --no-default-features --features postgres && cargo install just && just migrate'"
    working_dir: /app
    networks:
      - bridge
    volumes:
      - ./:/app
    environment:
      # format -> postgresql://DB_USER:DB_PASSWORD@HOST:PORT/DATABASE_NAME
      - DATABASE_URL=postgresql://hypersiwtch:1234@172.30.0.1:5432/hyperswitch_db

  ### Application services
  hyperswitch-server:
    image: juspaydotin/hyperswitch-router:standalone
    pull_policy: always
    command: /local/bin/router -f /local/config/docker_compose.toml
    ports:
      - "8017:8080"
    networks:
      - bridge
    volumes:
      - ./config:/local/config
      - ./files:/local/bin/files
    depends_on:
      pg:
        condition: service_healthy
      redis-standalone:
        condition: service_healthy
    labels:
      logs: "promtail"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 3
      start_period: 5s
      timeout: 5s

  hyperswitch-producer:
    image: juspaydotin/hyperswitch-producer:standalone
    pull_policy: always
    command: /local/bin/scheduler -f /local/config/docker_compose.toml
    networks:
      - bridge
    profiles:
      - scheduler
    volumes:
      - ./config:/local/config
    environment:
      - SCHEDULER_FLOW=producer
    depends_on:
      hyperswitch-consumer:
        condition: service_healthy
    labels:
      logs: "promtail"

  hyperswitch-consumer:
    image: juspaydotin/hyperswitch-consumer:standalone
    pull_policy: always
    command: /local/bin/scheduler -f /local/config/docker_compose.toml
    networks:
      - bridge
    profiles:
      - scheduler
    volumes:
      - ./config:/local/config
    environment:
      - SCHEDULER_FLOW=consumer
    depends_on:
      hyperswitch-server:
        condition: service_healthy
    labels:
      logs: "promtail"
    healthcheck:
      test: (ps -e | grep scheduler) || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 10s

  hyperswitch-drainer:
    image: juspaydotin/hyperswitch-drainer:standalone
    pull_policy: always
    command: /local/bin/drainer -f /local/config/docker_compose.toml
    deploy:
      replicas: ${DRAINER_INSTANCE_COUNT:-1}
    networks:
      - bridge
    profiles:
      - full_kv
    volumes:
      - ./config:/local/config
    restart: unless-stopped
    depends_on:
      hyperswitch-server:
        condition: service_healthy
    labels:
      logs: "promtail"

  ### Web Client
  hyperswitch-web:
    ports:
      - "9050:9050"
      - "9060:9060"
      - "5252:5252"
    networks:
      - bridge
    build:
      context: ./docker
      dockerfile: web.Dockerfile
    depends_on:
      hyperswitch-server:
        condition: service_healthy
    environment:
      - HYPERSWITCH_PUBLISHABLE_KEY=1AHNid#LGt#L8Q
      - HYPERSWITCH_SECRET_KEY=1AHNid#LGt#L8Q
      - HYPERSWITCH_SERVER_URL=https://invoice.marcelsoftware.dev
      - HYPERSWITCH_SERVER_URL_FOR_DEMO_APP=https://invoice.marcelsoftware.dev:8080
      - HYPERSWITCH_CLIENT_URL=http://localhost:9050
      - SELF_SERVER_URL=http://localhost:5252
      - SDK_ENV=local
      - ENV_LOGGING_URL=http://localhost:3103
      - ENV_BACKEND_URL=http://localhost:8080
    labels:
      logs: "promtail"

  ### Control Center
  hyperswitch-control-center:
    image: juspaydotin/hyperswitch-control-center:latest
    pull_policy: always
    ports:
      - "9000:9000"
    environment:
      - configPath=/tmp/dashboard-config.toml
    volumes:
      - ./config/dashboard.toml:/tmp/dashboard-config.toml
    depends_on:
      hyperswitch-server:
        condition: service_healthy
      hyperswitch-web:
        condition: service_started
    labels:
      logs: "promtail"

  ### Clustered Redis setup
  redis-cluster:
    image: redis:7
    deploy:
      replicas: ${REDIS_CLUSTER_COUNT:-3}
    command: redis-server /usr/local/etc/redis/redis.conf
    profiles:
      - clustered_redis
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - bridge
    ports:
      - "6379"
      - "16379"

  redis-init:
    image: redis:7
    profiles:
      - clustered_redis
    depends_on:
      - redis-cluster
    networks:
      - bridge
    command: |-
      bash -c 'export COUNT=${REDIS_CLUSTER_COUNT:-3}
      if [ $$COUNT -lt 3 ]
      then
      echo \"Minimum 3 nodes are needed for redis cluster\"
      exit 1
      fi
      HOSTS=\"\"
      for ((c=1; c<=$$COUNT;c++))
      do
      NODE=$COMPOSE_PROJECT_NAME-redis-cluster-$$c:6379
      echo $$NODE
      HOSTS=\"$$HOSTS $$NODE\"
      done
      echo Creating a cluster with $$HOSTS
      redis-cli --cluster create $$HOSTS --cluster-yes
      '
  ### Monitoring
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - bridge
    profiles:
      - monitoring
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100"
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - bridge
    profiles:
      - monitoring
    volumes:
      - ./config:/etc/loki

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: --config=/etc/otel-collector.yaml
    networks:
      - bridge
    profiles:
      - monitoring
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317"
      - "8888"
      - "8889"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - bridge
    profiles:
      - monitoring
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090"
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    networks:
      - bridge
    profiles:
      - monitoring
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
    restart: unless-stopped

  redis-insight:
    image: redislabs/redisinsight:latest
    networks:
      - bridge
    profiles:
      - monitoring
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_store:/db

  kafka0:
    image: confluentinc/cp-kafka:7.0.5
    hostname: kafka0
    networks:
      - bridge
    ports:
      - 9092:9092
      - 9093
      - 9997
      - 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:29093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka0:29092,CONTROLLER://kafka0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka0 -Dcom.sun.management.jmxremote.rmi.port=9997
    profiles:
      - olap
    volumes:
      - ./monitoring/kafka-script.sh:/tmp/update_run.sh
    command: 'bash -c ''if [ ! -f /tmp/update_run.sh ]; then echo "ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'''

  # Kafka UI for debugging kafka queues
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    networks:
      - bridge
    depends_on:
      - kafka0
    profiles:
      - olap
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      KAFKA_CLUSTERS_0_JMXPORT: 9997

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3
    networks:
      - bridge
    ports:
      - "9000"
      - "8123:8123"
    volumes:
      - ./crates/analytics/docs/clickhouse/scripts:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Kolkata
    profiles:
      - olap
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    hostname: opensearch
    environment:
      - "discovery.type=single-node"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=0penS3arc#
      - LOG_LEVEL=DEBUG
    profiles:
      - olap
    ports:
      - "9200:9200"
    networks:
      - bridge

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2
    ports:
      - 5601:5601
    profiles:
      - olap
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    networks:
      - bridge

  vector:
    image: timberio/vector:latest-debian
    ports:
      - "8686"
      - "9598"
      - "3103:3103"
    profiles:
      - olap
    environment:
      KAFKA_HOST: "kafka0:29092"
    networks:
      - bridge
    volumes:
      - ./config/vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock
```

**Reply by SanchithHegde** [reply]
> I also removed the pg service since I have the database locally

Since you removed the `pg` service, please update the database hostname in the config file accordingly:

https://github.com/juspay/hyperswitch/blob/72904842ed0092e16e2d9980e1d4968df03cafb6/config/docker_compose.toml#L24-L30

Replace `pg` with the suitable hostname, also update the username, password and database name if applicable. Ensure you update the database credentials in the `[master_database]`, `[replica_database]` and `[analytics.sqlx]` sections of the `config/docker_compose.toml` file.

Also, ensure that database migrations are run correctly. We make use of the `migration_runner` service / container to run database migrations, so you'd have to update the database credentials there as well.

**Comment by nitanmarcel** [comment]
What happens it just waits a while then I get `500` upon logging or creating a new account

**Reply by SanchithHegde** [reply]
The long wait time here is due to the application trying to connect to the database, and timing out after 30 seconds or so. 

Since you mentioned in your other comment that you'd removed the database container, but the config file hadn't been updated with the new database credentials, the application couldn't connect to the database obviously, and timed out.

**Reply by nitanmarcel** [reply]
> The long wait time here is due to the application trying to connect to the database, and timing out after 30 seconds or so.
> 
> Since you mentioned in your other comment that you'd removed the database container, but the config file hadn't been updated with the new database credentials, the application couldn't connect to the database obviously, and timed out.

Thanks. I've updated everything like in the last instructions. Any idea why this happens?

```
XHRPOST
https://invoiceapi.marcelsoftware.dev/user/signup
[HTTP/2 500  96ms]

	
error	Object { type: "api", message: "Something went wrong", code: "HE_00" }
type	"api"
message	"Something went wrong"
code	"HE_00"
```

**Reply by nitanmarcel** [reply]
> The long wait time here is due to the application trying to connect to the database, and timing out after 30 seconds or so.
> 
> Since you mentioned in your other comment that you'd removed the database container, but the config file hadn't been updated with the new database credentials, the application couldn't connect to the database obviously, and timed out.

looks like the error above was due to the migration. Anyway all that's left is:

```
XHRPOST
https://invoiceapi.marcelsoftware.dev/user/signout
[HTTP/2 401  45ms]

	
error	Object { type: "invalid_request", message: "Cookies are not found in the request", code: "IR_42" }
type	"invalid_request"
message	"Cookies are not found in the request"
code	"IR_42"
```

**Reply by SanchithHegde** [reply]
Could you update this line in the config file to `false`?

https://github.com/juspay/hyperswitch/blob/72904842ed0092e16e2d9980e1d4968df03cafb6/config/docker_compose.toml#L60

---

Preferably, we suggest users to check out to the `latest` tag and then run the Docker Compose setup, to reduce the number of configuration issues like this one. This is because our Docker Compose setup runs images for the stable releases, while the configuration files on the `main` branch evolve with the code changes landing on the `main` branch. So, it could be possible that the config files on the `main` branch may be incompatible with the Docker image corresponding to the stable release.

**Reply by nitanmarcel** [reply]
> `latest`

That worked thanks. ( I edited the api key and some other credentials and I'm getting the `HE_00` error again. but will wait and see maybe it fixes it. (I also wiped the database and started again)

about the `latest` tag, you mean the latest github tag? The docker images uses the `standalone` tag

**Reply by SanchithHegde** [reply]
> about the `latest` tag, you mean the latest github tag? The docker images uses the `standalone` tag

Yes, I mean the `latest` git tag on GitHub.

> The docker images uses the `standalone` tag

Yes, the Docker Compose setup uses the `standalone` image tag, which is built off the stable release version, which is the `v1.112.x` git tag as of today.

**Comment by nitanmarcel** [comment]
@SanchithHegde I have no idea how but after editing the `[secrets]` registration doesn't work anymore. Logging seems to work fine since it tells me that the user does not exist, but registration returns 500

```go
XHRPOST
https://invoiceapi.marcelsoftware.dev/user/signup
[HTTP/3 500  107ms]

	
POST
	https://invoiceapi.marcelsoftware.dev/user/signup
Status
500
VersionHTTP/3
Transferred527 B (72 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest
DNS ResolutionSystem

    	
    access-control-allow-credentials
    	true
    access-control-allow-origin
    	https://invoice.marcelsoftware.dev
    content-length
    	72
    content-type
    	application/json
    date
    	Fri, 17 Jan 2025 09:12:43 GMT
    server
    	Caddy
    strict-transport-security
    	max-age=31536000
    vary
    	Origin, Access-Control-Request-Method, Access-Control-Request-Headers
    via
    	HyperSwitch
    x-hyperswitch-version
    	v1.112.2-dirty
    x-request-id
    	01947389-4479-7d40-8812-146a93a96e22
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br, zstd
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	104
    Content-Type
    	application/json
    Host
    	invoiceapi.marcelsoftware.dev
    Origin
    	https://invoice.marcelsoftware.dev
    Priority
    	u=0
    Referer
    	https://invoice.marcelsoftware.dev/
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-site
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
```

```go
XHRPOST
https://invoiceapi.marcelsoftware.dev/user/signup
[HTTP/3 500  107ms]

	
error	Object { type: "api", message: "Something went wrong", code: "HE_00" }
type	"api"
message	"Something went wrong"
code	"HE_00"
```

```toml
[server]
port = 8080
host = "0.0.0.0"
request_body_limit = 16_384 # Post request body is limited to 16k.

[log.file]
enabled = false # Whether you want to store log in log files.
path = "logs"   # Where to store log files.
level = "DEBUG" # What gets into log files.
# rotation = "60"           # mins # current framework doesn't support configuring rotation. set to hourly rotation.

[log.console]
enabled = true  # Whether you want to see log in your terminal.
level = "INFO" # What you see in your terminal.

[log.telemetry]
traces_enabled = false                                      # Whether traces are enabled.
metrics_enabled = true                                      # Whether metrics are enabled.
ignore_errors = false                                       # Whether to ignore errors during traces or metrics pipeline setup.
otel_exporter_otlp_endpoint = "https://otel-collector:4317" # Endpoint to send metrics and traces to.
use_xray_generator = false                                  # Set this to true for AWS X-ray compatible traces
bg_metrics_collection_interval_in_secs = 15                 # Interval for collecting the metrics in background thread

[master_database]
username = "hyperswitch"
password = "1234"
host = "172.30.0.1"
port = 5432
dbname = "hyperswitch_db"
pool_size = 5

[forex_api]
call_delay = 21600
local_fetch_retry_count = 5
local_fetch_retry_delay = 1000
api_timeout = 20000
api_key = "YOUR API KEY HERE"
fallback_api_key = "YOUR API KEY HERE"
redis_lock_timeout = 26000

[replica_database]
username = "db_user"
password = "db_pass"
host = "pg"
port = 5432
dbname = "hyperswitch_db"
pool_size = 5

[secrets]
admin_api_key = "1234"
jwt_secret = "1234"
master_enc_key = "1234"

[user]
password_validity_in_days = 90
two_factor_auth_expiry_in_secs = 300
totp_issuer_name = "Hyperswitch"
base_url = "https://invoiceapi.marcelsoftware.dev"
force_two_factor_auth = false
force_cookies = false

[locker]
host = ""
host_rs = ""
mock_locker = true
basilisk_host = ""
locker_enabled = true
ttl_for_storage_in_secs = 220752000

[jwekey]
vault_encryption_key = ""
rust_locker_encryption_key = ""
vault_private_key = ""

[redis]
host = "redis-standalone"
port = 6379
cluster_enabled = false
cluster_urls = ["redis-cluster:6379"]
pool_size = 5
reconnect_max_attempts = 5
reconnect_delay = 5
default_ttl = 300
default_hash_ttl = 900
use_legacy_version = false
stream_read_count = 1
auto_pipeline = true
disable_auto_backpressure = false
max_in_flight_commands = 5000
default_command_timeout = 30
unresponsive_timeout = 10
max_feed_count = 200

[key_manager]
url = "http://localhost:5000"

[cors]
max_age = 30
origins = "http://localhost:8080,http://localhost:9000,https://invoice.marcelsoftware.dev,https://marcelsoftware.dev"
allowed_methods = "GET,POST,PUT,DELETE"
wildcard_origin = false

[refund]
max_attempts = 10
max_age = 365

[api_keys]
hash_key = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
```
