### ISSUE TITLE
[BUG] Docker compose failing because of the web module not having healthcheck

### ISSUE THREAD

**Issue by NedimBadzak** [juspay/hyperswitch#7945]
### Bug Description

When `docker compose up -d` is ran, it returns the following error message:
`dependency failed to start: container hyperswitch-hyperswitch-web-1 has no healthcheck configured`

### Expected Behavior

The Web module should be started

### Actual Behavior

The Web module doesn't start due to this

### Steps To Reproduce

1. Clone repo from scratch
2. Run `docker compose up -d`

### Context For The Bug

This can be resolved with either adding a healthcheck part to the web module or changing the demo part to not require healthcheck from the web part. Additionally, we could only check if it has started rather than if it is healthy, as that is something which works.

### Environment

I am running this locally.

1. Operating System or Linux distribution: Mac OS X 15.4 M3 Pro
2. Rust version (output of `rustc --version`): /
3. App version (output of `cargo r --features vergen -- --version`): /

### Have you spent some time checking if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [x] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by VikashMediboina** [comment]
The same issue with me as well.

**Comment by djcrafts** [comment]
I found the issue! The demo container is waiting for the web container to pass its health check, but the web container doesn't have any health check configured.

We can fix this in two simple ways:

1. Add a health check to the web container:
```
web:
  # other settings remain the same
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 15s
```
2. Or make the demo container just wait for the web container to start (instead of waiting for it to be healthy):
```
demo:
  # other settings remain the same
  depends_on:
    web:
      condition: service_started
```

Let's discuss which approach is better for the project. Option 1 ensures the web service is actually working before starting the demo, while option 2 is simpler but might cause issues if the demo needs a fully functional web service.
